### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by pkomur**
Contains new strings

### CODE REVIEW

**Comment by aleho** [comment]
Please merge your commits into one and force push to your branch.

I'm going to add a pot file as well to make future translations easier.

**Comment by pkomur** [comment]
I closed request #72 , so please commit request #73.

**Comment by aleho** [comment]
Yes, I'm aware of that.

Please rebase your commits onto the current master and squash them to one commit "Add Polish translations".

**Comment by pkomur** [comment]
I think it's OK now.

**Comment by aleho** [comment]
If you look at your pull request it now contains even more commits.

**Comment by pkomur** [comment]
Because my branch was not synchronized.

**Comment by aleho** [comment]
Hence the request to rebase it. No worries, I'm going to manually commit the translations.

**Pull request closed without merging**
