### PR TITLE
Fix Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by ricvelozo**
The translation was not loading. Also, I added my name and a short description in the comment.

### CODE REVIEW

**Comment by tingvarsson** [comment]
Breaks the AUR PKGBUILD as well as it presumes the translation files to be located as corrected in this PR. @aleho Please if you could act on this, thanks.

**Comment by tingvarsson** [comment]
@aleho why no action on this?

**Comment by aleho** [comment]
I'll merge this once the release for 3.30 is done.

I'm not going to do a release in between, because the publishing process in Gnome takes ages, and (gut feeling) even longer if you do multiple releases in a short period of time.

**Comment by WoefulDerelict** [comment]
@tingvarsson There is a much simpler PKGBUILD for this extension located here [https://gist.github.com/WoefulDerelict/3a3e4986c18e8841b927becd2afeeaad] you are welcome to use which I believe addresses your issue with the one currently posted to the AUR.

**Comment by tingvarsson** [comment]
@WoefulDerelict Thanks for the fyi! Why not make them into upstream AUR?

**Comment by WoefulDerelict** [comment]
@tingvarsson I'm not the maintainer for the PKGBUILD in the AUR. The current maintainer uses some sort of scripting to try and automatically update things as part of some collection with it's upstream here on GitHub. I just happened to cobble together my own take on the process as I don't like the way that PKGBUILD reads and find it easier to manage something smaller by hand at a pace more in line with how often I update my systems. I wasn't annoyed enough to file an orphan request and take the PKGBUILDs on myself.

**Pull request merged**
