### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by pkomur**
Thanks and sorry for the confusion.

### CODE REVIEW

**Comment by aleho** [comment]
Closed with 8bda28977ba29ff34fa94f6a4516675c4b1ba183

**Comment by aleho** [comment]
@pkomur If you want I can add you to the translators in the Crowdin project.

**Comment by pkomur** [comment]
OK, please add.

**Comment by aleho** [comment]
@pkomur Send me your email address you'd like to use for Crowdin.

**Comment by pkomur** [comment]
pkomur@gmail.com

15.11.2017 3:40 PM "Alexander Hofbauer" <notifications@github.com>
napisał(a):

**Pull request closed without merging**
